---
- hosts: webserver-current
  serial: 1
  tasks:
  - name: take webserver out of loadbalancer
    local_action:
      module: cs_loadbalancer_rule_member
      name: balance_http
      vm: "{{ inventory_hostname_short }}"
      state: absent
      project: "{{ cs_project }}"
      zone: "{{ cs_zone }}"

  - name: Create a VM snapshot before an upgrade
    local_action:
      module: cs_vmsnapshot
      name: Snapshot before upgrade
      vm: "{{ inventory_hostname_short }}"
      snapshot_memory: yes
      project: "{{ cs_project }}"
      zone: "{{ cs_zone }}"

  - block:
    - name: upgrade application
      copy:
        content: "{{ inventory_hostname_short }} upgraded"
        dest: /usr/share/nginx/html/index.html
      failed_when: "inventory_hostname_short == 'web-eq-01'"

    - name: smoke tests
      debug: msg="run some smoke tests..."
      failed_when: "inventory_hostname_short == 'web-eq-01'"

    rescue:
    - name: Revert a VM to a snapshot after a failed upgrade
      local_action:
        module: cs_vmsnapshot
        name: Snapshot before upgrade
        vm: "{{ inventory_hostname_short }}"
        state: revert
        project: "{{ cs_project }}"
        zone: "{{ cs_zone }}"

    - name: Remove a VM snapshot after successful rollback
      local_action:
        module: cs_vmsnapshot
        name: Snapshot before upgrade
        vm: "{{ inventory_hostname_short }}"
        state: absent
        project: "{{ cs_project }}"
        zone: "{{ cs_zone }}"

  - name: re-add webserver to loadbalancer
    local_action:
      module: cs_loadbalancer_rule_member
      name: balance_http
      vm: "{{ inventory_hostname_short }}"
      state: present
      project: "{{ cs_project }}"
      zone: "{{ cs_zone }}"

  - name: Remove a VM snapshot after successful upgrade
    local_action:
      module: cs_vmsnapshot
      name: Snapshot before upgrade
      vm: "{{ inventory_hostname_short }}"
      state: absent
      project: "{{ cs_project }}"
      zone: "{{ cs_zone }}"

