---
- hosts: webserver-current
  pre_tasks:
    - name: add loadbalancer rule
      local_action:
        module: cs_loadbalancer_rule
        name: balance_http
        public_ip: "{{ web_cluster_ip }}"
        algorithm: roundrobin
        public_port: 80
        private_port: 80
        open_firewall: yes
        project: "{{ cs_project }}"
        zone: "{{ cs_zone }}"
      run_once: yes
  roles:
    - app
  tasks:
    - name: add VMs to load balancer
      local_action:
        module: cs_loadbalancer_rule_member
        name: balance_http
        vms: "{{ inventory_hostname_short }}"
        project: "{{ cs_project }}"
        zone: "{{ cs_zone }}"

- hosts: webserver-upgraded
  gather_facts: no
  tasks:
    - name: remove VMs to load balancer
      local_action:
        module: cs_loadbalancer_rule_member
        name: balance_http
        vms: "{{ inventory_hostname_short }}"
        project: "{{ cs_project }}"
        zone: "{{ cs_zone }}"
        state: absent

    - name: ensure VM instance is absent
      local_action:
        module: cs_instance
        name: "{{ inventory_hostname_short }}"
        zone: "{{ cs_zone }}"
        project: "{{ cs_project }}"
        state: expunged
