---
kind: ConfigMap
apiVersion: v1
metadata:
  name: traefik-cfg
  labels:
    app: traefik-ingress
data:
  traefik.toml: |
    defaultEntryPoints = ["http"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
    [web]
    address = ":2727"
    ReadOnly = true
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: traefik-ingress-controller
  labels:
    app: traefik-ingress
spec:
  template:
    metadata:
      labels:
        app: traefik-ingress
        name: traefik-ingress
    spec:
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      volumes:
      - name: config
        configMap:
          name: traefik-cfg
      containers:
      - image: traefik
        name: traefik-ingress
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/config"
          name: "config"
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 2727
          hostPort: 2727
        args:
        - --configfile=/config/traefik.toml
        - --kubernetes
